/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package appComponent;

import java.awt.Color;
import model.Model_User_Account;

/**
 *
 * @author Abdella Omer
 */
public class Chat_Title extends javax.swing.JPanel {

    /**
     * @return the user
     */
    public Model_User_Account getUser() {
        return user;
    }

    /**
     * Creates new form Chat_Title
     */
    private Model_User_Account user;
    public Chat_Title() {
        initComponents();
    }
    
     public void setUserName(Model_User_Account user) {
         this.user= user;
        lbname.setText(user.getUserName());
        if(user.isStatus()){
            statusActive();
        }else{
            setStatusText("Offline");
        }
    }
     
      public void updateUser(Model_User_Account user) {
        if (this.user == user) {
            lbname.setText(user.getUserName());
            if (user.isStatus()) {
                statusActive();
            } else {
                setStatusText("Offline");
            }
        }
    }

    public void statusActive() {
        lbstatus.setText("Active now");
        lbstatus.setForeground(new java.awt.Color(40, 147, 59));
    }

    public void setStatusText(String text) {
        lbstatus.setText(text);
        lbstatus.setForeground(new Color(160, 160, 160));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layer = new javax.swing.JLayeredPane();
        lbname = new javax.swing.JLabel();
        lbstatus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(231, 239, 196));

        layer.setLayout(new java.awt.GridLayout(0, 1));

        lbname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbname.setText("Name");
        layer.add(lbname);

        lbstatus.setForeground(new java.awt.Color(51, 153, 0));
        lbstatus.setText("Active now");
        layer.add(lbstatus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layer)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane layer;
    private javax.swing.JLabel lbname;
    private javax.swing.JLabel lbstatus;
    // End of variables declaration//GEN-END:variables
}
